apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-backend-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: synapse-backend

  template:
    metadata:
      labels:
        app: synapse-backend

    spec:
      containers:
        - name: synapse-backend
          image: synapse-backend:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: synapse

---
apiVersion: v1
kind: Service

metadata:
  name: synapse-ai-service

spec:
  selector:
    app: synapse-ai

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8088
      nodePort: 30088 

  type: NodePort