spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/synapseai}
        username: ${SPRING_DATASOURCE_USERNAME:aaris}
        password: ${SPRING_DATASOURCE_PASSWORD:12345}
        driver-class-name: com.mysql.cj.jdbc.Driver

    security:
        user:
            name: ${name:aaris}
            password: ${password:aarisPassword}

        oauth2:
            client:
                registration:
                    google:
                        client-id: ${CLIENT_ID:something}
                        client-secret: ${CLIENT_SECRET:something}

app:
    secret: ${SECRETS:something}
    expiration: 24
    llm: "ollama"
    openai:
        api-key: ${OPENAPI_SECRET:something}
        model: gpt-4.1-mini
    ollama:
        type: cloud
        base-url: https://ollama.com
        local-url: http://192.168.0.114:11434
        api-key: ${OLLAMA_KEYS:something}
        model: ${OLLAMA_MODEL:gpt-oss:120b}

