spring.application.name=synapse_backend

# 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