server:
  address: 0.0.0.0
  port: 8080

spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    security:
        user:
            name: ${name:aaris}
            password: ${password:aarisPassword}

        oauth2:
            client:
                registration:
                    google:
                        client-id: ${CLIENT_ID}
                        client-secret: ${CLIENT_SECRET}
                        scope: profile, email

app:
    secret: ${SECRETS:mysecret}
    expiration: 7

